// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: mensajes.proto

package PokemonProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mensajes_proto protoreflect.FileDescriptor

const file_mensajes_proto_rawDesc = "" +
	"\n" +
	"\x0emensajes.proto\x12\apokemon\x1a\vtipos.proto2\xa3\x03\n" +
	"\vServicioLCP\x127\n" +
	"\x0eObtenerTorneos\x12\x0e.pokemon.Empty\x1a\x15.pokemon.ListaTorneos\x12D\n" +
	"\x14ObtenerTorneosRegion\x12\x15.pokemon.RegionString\x1a\x15.pokemon.ListaTorneos\x12I\n" +
	"\x11InscribirEnTorneo\x12\x1a.pokemon.InscripcionTorneo\x1a\x18.pokemon.CodigoRespuesta\x12D\n" +
	"\x13RegistrarEntrenador\x12\x13.pokemon.Entrenador\x1a\x18.pokemon.CodigoRespuesta\x12C\n" +
	"\x10ExisteEntrenador\x12\x15.pokemon.EntrenadorID\x1a\x18.pokemon.CodigoRespuesta\x12?\n" +
	"\x11ObtenerEntrenador\x12\x15.pokemon.EntrenadorID\x1a\x13.pokemon.Entrenador2N\n" +
	"\vServicioGym\x12?\n" +
	"\x0eAsignarCombate\x12\x13.pokemon.CombateGym\x1a\x18.pokemon.CodigoRespuestaB\x17Z\x15mensajes/PokemonProtob\x06proto3"

var file_mensajes_proto_goTypes = []any{
	(*Empty)(nil),             // 0: pokemon.Empty
	(*RegionString)(nil),      // 1: pokemon.RegionString
	(*InscripcionTorneo)(nil), // 2: pokemon.InscripcionTorneo
	(*Entrenador)(nil),        // 3: pokemon.Entrenador
	(*EntrenadorID)(nil),      // 4: pokemon.EntrenadorID
	(*CombateGym)(nil),        // 5: pokemon.CombateGym
	(*ListaTorneos)(nil),      // 6: pokemon.ListaTorneos
	(*CodigoRespuesta)(nil),   // 7: pokemon.CodigoRespuesta
}
var file_mensajes_proto_depIdxs = []int32{
	0, // 0: pokemon.ServicioLCP.ObtenerTorneos:input_type -> pokemon.Empty
	1, // 1: pokemon.ServicioLCP.ObtenerTorneosRegion:input_type -> pokemon.RegionString
	2, // 2: pokemon.ServicioLCP.InscribirEnTorneo:input_type -> pokemon.InscripcionTorneo
	3, // 3: pokemon.ServicioLCP.RegistrarEntrenador:input_type -> pokemon.Entrenador
	4, // 4: pokemon.ServicioLCP.ExisteEntrenador:input_type -> pokemon.EntrenadorID
	4, // 5: pokemon.ServicioLCP.ObtenerEntrenador:input_type -> pokemon.EntrenadorID
	5, // 6: pokemon.ServicioGym.AsignarCombate:input_type -> pokemon.CombateGym
	6, // 7: pokemon.ServicioLCP.ObtenerTorneos:output_type -> pokemon.ListaTorneos
	6, // 8: pokemon.ServicioLCP.ObtenerTorneosRegion:output_type -> pokemon.ListaTorneos
	7, // 9: pokemon.ServicioLCP.InscribirEnTorneo:output_type -> pokemon.CodigoRespuesta
	7, // 10: pokemon.ServicioLCP.RegistrarEntrenador:output_type -> pokemon.CodigoRespuesta
	7, // 11: pokemon.ServicioLCP.ExisteEntrenador:output_type -> pokemon.CodigoRespuesta
	3, // 12: pokemon.ServicioLCP.ObtenerEntrenador:output_type -> pokemon.Entrenador
	7, // 13: pokemon.ServicioGym.AsignarCombate:output_type -> pokemon.CodigoRespuesta
	7, // [7:14] is the sub-list for method output_type
	0, // [0:7] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mensajes_proto_init() }
func file_mensajes_proto_init() {
	if File_mensajes_proto != nil {
		return
	}
	file_tipos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mensajes_proto_rawDesc), len(file_mensajes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mensajes_proto_goTypes,
		DependencyIndexes: file_mensajes_proto_depIdxs,
	}.Build()
	File_mensajes_proto = out.File
	file_mensajes_proto_goTypes = nil
	file_mensajes_proto_depIdxs = nil
}
