// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/mensajes.proto

package servicioMensajes

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GobiernoService_ObtenerListaPiratas_FullMethodName      = "/serviciomensajes.GobiernoService/ObtenerListaPiratas"
	GobiernoService_ObtenerListaPiratasTodos_FullMethodName = "/serviciomensajes.GobiernoService/ObtenerListaPiratasTodos"
	GobiernoService_ResultadoEntrega_FullMethodName         = "/serviciomensajes.GobiernoService/ResultadoEntrega"
	GobiernoService_Basic_FullMethodName                    = "/serviciomensajes.GobiernoService/Basic"
	GobiernoService_ObtenerNpiratasRestantes_FullMethodName = "/serviciomensajes.GobiernoService/ObtenerNpiratasRestantes"
	GobiernoService_MarcarCaptura_FullMethodName            = "/serviciomensajes.GobiernoService/MarcarCaptura"
)

// GobiernoServiceClient is the client API for GobiernoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GobiernoServiceClient interface {
	ObtenerListaPiratas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaPiratas, error)
	ObtenerListaPiratasTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaPiratas, error)
	ResultadoEntrega(ctx context.Context, in *ActualizarReputacionRequest, opts ...grpc.CallOption) (*ActualizarReputacionResponse, error)
	Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error)
	ObtenerNpiratasRestantes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NpiratasRestantes, error)
	MarcarCaptura(ctx context.Context, in *PirataCapturado, opts ...grpc.CallOption) (*Empty, error)
}

type gobiernoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGobiernoServiceClient(cc grpc.ClientConnInterface) GobiernoServiceClient {
	return &gobiernoServiceClient{cc}
}

func (c *gobiernoServiceClient) ObtenerListaPiratas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaPiratas, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaPiratas)
	err := c.cc.Invoke(ctx, GobiernoService_ObtenerListaPiratas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) ObtenerListaPiratasTodos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaPiratas, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaPiratas)
	err := c.cc.Invoke(ctx, GobiernoService_ObtenerListaPiratasTodos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) ResultadoEntrega(ctx context.Context, in *ActualizarReputacionRequest, opts ...grpc.CallOption) (*ActualizarReputacionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarReputacionResponse)
	err := c.cc.Invoke(ctx, GobiernoService_ResultadoEntrega_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, GobiernoService_Basic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) ObtenerNpiratasRestantes(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NpiratasRestantes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NpiratasRestantes)
	err := c.cc.Invoke(ctx, GobiernoService_ObtenerNpiratasRestantes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gobiernoServiceClient) MarcarCaptura(ctx context.Context, in *PirataCapturado, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GobiernoService_MarcarCaptura_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GobiernoServiceServer is the server API for GobiernoService service.
// All implementations must embed UnimplementedGobiernoServiceServer
// for forward compatibility.
type GobiernoServiceServer interface {
	ObtenerListaPiratas(context.Context, *Empty) (*ListaPiratas, error)
	ObtenerListaPiratasTodos(context.Context, *Empty) (*ListaPiratas, error)
	ResultadoEntrega(context.Context, *ActualizarReputacionRequest) (*ActualizarReputacionResponse, error)
	Basic(context.Context, *BasicRequest) (*BasicResponse, error)
	ObtenerNpiratasRestantes(context.Context, *Empty) (*NpiratasRestantes, error)
	MarcarCaptura(context.Context, *PirataCapturado) (*Empty, error)
	mustEmbedUnimplementedGobiernoServiceServer()
}

// UnimplementedGobiernoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGobiernoServiceServer struct{}

func (UnimplementedGobiernoServiceServer) ObtenerListaPiratas(context.Context, *Empty) (*ListaPiratas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerListaPiratas not implemented")
}
func (UnimplementedGobiernoServiceServer) ObtenerListaPiratasTodos(context.Context, *Empty) (*ListaPiratas, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerListaPiratasTodos not implemented")
}
func (UnimplementedGobiernoServiceServer) ResultadoEntrega(context.Context, *ActualizarReputacionRequest) (*ActualizarReputacionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResultadoEntrega not implemented")
}
func (UnimplementedGobiernoServiceServer) Basic(context.Context, *BasicRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Basic not implemented")
}
func (UnimplementedGobiernoServiceServer) ObtenerNpiratasRestantes(context.Context, *Empty) (*NpiratasRestantes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerNpiratasRestantes not implemented")
}
func (UnimplementedGobiernoServiceServer) MarcarCaptura(context.Context, *PirataCapturado) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarcarCaptura not implemented")
}
func (UnimplementedGobiernoServiceServer) mustEmbedUnimplementedGobiernoServiceServer() {}
func (UnimplementedGobiernoServiceServer) testEmbeddedByValue()                         {}

// UnsafeGobiernoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GobiernoServiceServer will
// result in compilation errors.
type UnsafeGobiernoServiceServer interface {
	mustEmbedUnimplementedGobiernoServiceServer()
}

func RegisterGobiernoServiceServer(s grpc.ServiceRegistrar, srv GobiernoServiceServer) {
	// If the following call pancis, it indicates UnimplementedGobiernoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GobiernoService_ServiceDesc, srv)
}

func _GobiernoService_ObtenerListaPiratas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ObtenerListaPiratas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ObtenerListaPiratas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ObtenerListaPiratas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_ObtenerListaPiratasTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ObtenerListaPiratasTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ObtenerListaPiratasTodos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ObtenerListaPiratasTodos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_ResultadoEntrega_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarReputacionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ResultadoEntrega(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ResultadoEntrega_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ResultadoEntrega(ctx, req.(*ActualizarReputacionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_Basic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).Basic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_Basic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).Basic(ctx, req.(*BasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_ObtenerNpiratasRestantes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).ObtenerNpiratasRestantes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_ObtenerNpiratasRestantes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).ObtenerNpiratasRestantes(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GobiernoService_MarcarCaptura_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PirataCapturado)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GobiernoServiceServer).MarcarCaptura(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GobiernoService_MarcarCaptura_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GobiernoServiceServer).MarcarCaptura(ctx, req.(*PirataCapturado))
	}
	return interceptor(ctx, in, info, handler)
}

// GobiernoService_ServiceDesc is the grpc.ServiceDesc for GobiernoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GobiernoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviciomensajes.GobiernoService",
	HandlerType: (*GobiernoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerListaPiratas",
			Handler:    _GobiernoService_ObtenerListaPiratas_Handler,
		},
		{
			MethodName: "ObtenerListaPiratasTodos",
			Handler:    _GobiernoService_ObtenerListaPiratasTodos_Handler,
		},
		{
			MethodName: "ResultadoEntrega",
			Handler:    _GobiernoService_ResultadoEntrega_Handler,
		},
		{
			MethodName: "Basic",
			Handler:    _GobiernoService_Basic_Handler,
		},
		{
			MethodName: "ObtenerNpiratasRestantes",
			Handler:    _GobiernoService_ObtenerNpiratasRestantes_Handler,
		},
		{
			MethodName: "MarcarCaptura",
			Handler:    _GobiernoService_MarcarCaptura_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mensajes.proto",
}

const (
	MarinaService_EntregarPirata_FullMethodName  = "/serviciomensajes.MarinaService/EntregarPirata"
	MarinaService_ActividadIlegal_FullMethodName = "/serviciomensajes.MarinaService/ActividadIlegal"
	MarinaService_Basic_FullMethodName           = "/serviciomensajes.MarinaService/Basic"
)

// MarinaServiceClient is the client API for MarinaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarinaServiceClient interface {
	EntregarPirata(ctx context.Context, in *EntregaRequest, opts ...grpc.CallOption) (*EntregaResponse, error)
	ActividadIlegal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error)
}

type marinaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarinaServiceClient(cc grpc.ClientConnInterface) MarinaServiceClient {
	return &marinaServiceClient{cc}
}

func (c *marinaServiceClient) EntregarPirata(ctx context.Context, in *EntregaRequest, opts ...grpc.CallOption) (*EntregaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntregaResponse)
	err := c.cc.Invoke(ctx, MarinaService_EntregarPirata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marinaServiceClient) ActividadIlegal(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, MarinaService_ActividadIlegal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marinaServiceClient) Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, MarinaService_Basic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarinaServiceServer is the server API for MarinaService service.
// All implementations must embed UnimplementedMarinaServiceServer
// for forward compatibility.
type MarinaServiceServer interface {
	EntregarPirata(context.Context, *EntregaRequest) (*EntregaResponse, error)
	ActividadIlegal(context.Context, *Empty) (*Empty, error)
	Basic(context.Context, *BasicRequest) (*BasicResponse, error)
	mustEmbedUnimplementedMarinaServiceServer()
}

// UnimplementedMarinaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarinaServiceServer struct{}

func (UnimplementedMarinaServiceServer) EntregarPirata(context.Context, *EntregaRequest) (*EntregaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntregarPirata not implemented")
}
func (UnimplementedMarinaServiceServer) ActividadIlegal(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActividadIlegal not implemented")
}
func (UnimplementedMarinaServiceServer) Basic(context.Context, *BasicRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Basic not implemented")
}
func (UnimplementedMarinaServiceServer) mustEmbedUnimplementedMarinaServiceServer() {}
func (UnimplementedMarinaServiceServer) testEmbeddedByValue()                       {}

// UnsafeMarinaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarinaServiceServer will
// result in compilation errors.
type UnsafeMarinaServiceServer interface {
	mustEmbedUnimplementedMarinaServiceServer()
}

func RegisterMarinaServiceServer(s grpc.ServiceRegistrar, srv MarinaServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarinaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarinaService_ServiceDesc, srv)
}

func _MarinaService_EntregarPirata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntregaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarinaServiceServer).EntregarPirata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarinaService_EntregarPirata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarinaServiceServer).EntregarPirata(ctx, req.(*EntregaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarinaService_ActividadIlegal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarinaServiceServer).ActividadIlegal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarinaService_ActividadIlegal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarinaServiceServer).ActividadIlegal(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarinaService_Basic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarinaServiceServer).Basic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarinaService_Basic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarinaServiceServer).Basic(ctx, req.(*BasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarinaService_ServiceDesc is the grpc.ServiceDesc for MarinaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarinaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviciomensajes.MarinaService",
	HandlerType: (*MarinaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntregarPirata",
			Handler:    _MarinaService_EntregarPirata_Handler,
		},
		{
			MethodName: "ActividadIlegal",
			Handler:    _MarinaService_ActividadIlegal_Handler,
		},
		{
			MethodName: "Basic",
			Handler:    _MarinaService_Basic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mensajes.proto",
}

const (
	SubMundoService_EntregarPirata_FullMethodName = "/serviciomensajes.SubMundoService/EntregarPirata"
	SubMundoService_ActivarRedadas_FullMethodName = "/serviciomensajes.SubMundoService/ActivarRedadas"
	SubMundoService_Basic_FullMethodName          = "/serviciomensajes.SubMundoService/Basic"
)

// SubMundoServiceClient is the client API for SubMundoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubMundoServiceClient interface {
	EntregarPirata(ctx context.Context, in *EntregaRequest, opts ...grpc.CallOption) (*EntregaResponse, error)
	ActivarRedadas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error)
}

type subMundoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubMundoServiceClient(cc grpc.ClientConnInterface) SubMundoServiceClient {
	return &subMundoServiceClient{cc}
}

func (c *subMundoServiceClient) EntregarPirata(ctx context.Context, in *EntregaRequest, opts ...grpc.CallOption) (*EntregaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntregaResponse)
	err := c.cc.Invoke(ctx, SubMundoService_EntregarPirata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subMundoServiceClient) ActivarRedadas(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SubMundoService_ActivarRedadas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subMundoServiceClient) Basic(ctx context.Context, in *BasicRequest, opts ...grpc.CallOption) (*BasicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BasicResponse)
	err := c.cc.Invoke(ctx, SubMundoService_Basic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubMundoServiceServer is the server API for SubMundoService service.
// All implementations must embed UnimplementedSubMundoServiceServer
// for forward compatibility.
type SubMundoServiceServer interface {
	EntregarPirata(context.Context, *EntregaRequest) (*EntregaResponse, error)
	ActivarRedadas(context.Context, *Empty) (*Empty, error)
	Basic(context.Context, *BasicRequest) (*BasicResponse, error)
	mustEmbedUnimplementedSubMundoServiceServer()
}

// UnimplementedSubMundoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubMundoServiceServer struct{}

func (UnimplementedSubMundoServiceServer) EntregarPirata(context.Context, *EntregaRequest) (*EntregaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntregarPirata not implemented")
}
func (UnimplementedSubMundoServiceServer) ActivarRedadas(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivarRedadas not implemented")
}
func (UnimplementedSubMundoServiceServer) Basic(context.Context, *BasicRequest) (*BasicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Basic not implemented")
}
func (UnimplementedSubMundoServiceServer) mustEmbedUnimplementedSubMundoServiceServer() {}
func (UnimplementedSubMundoServiceServer) testEmbeddedByValue()                         {}

// UnsafeSubMundoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubMundoServiceServer will
// result in compilation errors.
type UnsafeSubMundoServiceServer interface {
	mustEmbedUnimplementedSubMundoServiceServer()
}

func RegisterSubMundoServiceServer(s grpc.ServiceRegistrar, srv SubMundoServiceServer) {
	// If the following call pancis, it indicates UnimplementedSubMundoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SubMundoService_ServiceDesc, srv)
}

func _SubMundoService_EntregarPirata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntregaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubMundoServiceServer).EntregarPirata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubMundoService_EntregarPirata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubMundoServiceServer).EntregarPirata(ctx, req.(*EntregaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubMundoService_ActivarRedadas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubMundoServiceServer).ActivarRedadas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubMundoService_ActivarRedadas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubMundoServiceServer).ActivarRedadas(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SubMundoService_Basic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BasicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubMundoServiceServer).Basic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SubMundoService_Basic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubMundoServiceServer).Basic(ctx, req.(*BasicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubMundoService_ServiceDesc is the grpc.ServiceDesc for SubMundoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubMundoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serviciomensajes.SubMundoService",
	HandlerType: (*SubMundoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntregarPirata",
			Handler:    _SubMundoService_EntregarPirata_Handler,
		},
		{
			MethodName: "ActivarRedadas",
			Handler:    _SubMundoService_ActivarRedadas_Handler,
		},
		{
			MethodName: "Basic",
			Handler:    _SubMundoService_Basic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mensajes.proto",
}
