// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: tipos.proto

package PokemonProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstadoEntrenador int32

const (
	EstadoEntrenador_ENTRENADOR_ACTIVO     EstadoEntrenador = 0
	EstadoEntrenador_ENTRENADOR_INACTIVO   EstadoEntrenador = 1
	EstadoEntrenador_ENTRENADOR_SUSPENDIDO EstadoEntrenador = 2
)

// Enum value maps for EstadoEntrenador.
var (
	EstadoEntrenador_name = map[int32]string{
		0: "ENTRENADOR_ACTIVO",
		1: "ENTRENADOR_INACTIVO",
		2: "ENTRENADOR_SUSPENDIDO",
	}
	EstadoEntrenador_value = map[string]int32{
		"ENTRENADOR_ACTIVO":     0,
		"ENTRENADOR_INACTIVO":   1,
		"ENTRENADOR_SUSPENDIDO": 2,
	}
)

func (x EstadoEntrenador) Enum() *EstadoEntrenador {
	p := new(EstadoEntrenador)
	*p = x
	return p
}

func (x EstadoEntrenador) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstadoEntrenador) Descriptor() protoreflect.EnumDescriptor {
	return file_tipos_proto_enumTypes[0].Descriptor()
}

func (EstadoEntrenador) Type() protoreflect.EnumType {
	return &file_tipos_proto_enumTypes[0]
}

func (x EstadoEntrenador) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstadoEntrenador.Descriptor instead.
func (EstadoEntrenador) EnumDescriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{0}
}

type EstadoTorneo int32

const (
	EstadoTorneo_TORNEO_ACTIVO     EstadoTorneo = 0
	EstadoTorneo_TORNEO_PENDIENTE  EstadoTorneo = 1
	EstadoTorneo_TORNEO_FINALIZADO EstadoTorneo = 2
)

// Enum value maps for EstadoTorneo.
var (
	EstadoTorneo_name = map[int32]string{
		0: "TORNEO_ACTIVO",
		1: "TORNEO_PENDIENTE",
		2: "TORNEO_FINALIZADO",
	}
	EstadoTorneo_value = map[string]int32{
		"TORNEO_ACTIVO":     0,
		"TORNEO_PENDIENTE":  1,
		"TORNEO_FINALIZADO": 2,
	}
)

func (x EstadoTorneo) Enum() *EstadoTorneo {
	p := new(EstadoTorneo)
	*p = x
	return p
}

func (x EstadoTorneo) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstadoTorneo) Descriptor() protoreflect.EnumDescriptor {
	return file_tipos_proto_enumTypes[1].Descriptor()
}

func (EstadoTorneo) Type() protoreflect.EnumType {
	return &file_tipos_proto_enumTypes[1]
}

func (x EstadoTorneo) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstadoTorneo.Descriptor instead.
func (EstadoTorneo) EnumDescriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{1}
}

type Entrenador struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	Ranking       int32                  `protobuf:"varint,4,opt,name=ranking,proto3" json:"ranking,omitempty"`
	Estado        EstadoEntrenador       `protobuf:"varint,5,opt,name=estado,proto3,enum=pokemon.EstadoEntrenador" json:"estado,omitempty"`
	Suspencion    int32                  `protobuf:"varint,6,opt,name=suspencion,proto3" json:"suspencion,omitempty"` //permanente
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entrenador) Reset() {
	*x = Entrenador{}
	mi := &file_tipos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entrenador) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrenador) ProtoMessage() {}

func (x *Entrenador) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrenador.ProtoReflect.Descriptor instead.
func (*Entrenador) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{0}
}

func (x *Entrenador) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entrenador) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Entrenador) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Entrenador) GetRanking() int32 {
	if x != nil {
		return x.Ranking
	}
	return 0
}

func (x *Entrenador) GetEstado() EstadoEntrenador {
	if x != nil {
		return x.Estado
	}
	return EstadoEntrenador_ENTRENADOR_ACTIVO
}

func (x *Entrenador) GetSuspencion() int32 {
	if x != nil {
		return x.Suspencion
	}
	return 0
}

type CombateGym struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Entrenador_1  *Entrenador            `protobuf:"bytes,2,opt,name=entrenador_1,json=entrenador1,proto3" json:"entrenador_1,omitempty"`
	Entrenador_2  *Entrenador            `protobuf:"bytes,3,opt,name=entrenador_2,json=entrenador2,proto3" json:"entrenador_2,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombateGym) Reset() {
	*x = CombateGym{}
	mi := &file_tipos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombateGym) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombateGym) ProtoMessage() {}

func (x *CombateGym) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombateGym.ProtoReflect.Descriptor instead.
func (*CombateGym) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{1}
}

func (x *CombateGym) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CombateGym) GetEntrenador_1() *Entrenador {
	if x != nil {
		return x.Entrenador_1
	}
	return nil
}

func (x *CombateGym) GetEntrenador_2() *Entrenador {
	if x != nil {
		return x.Entrenador_2
	}
	return nil
}

func (x *CombateGym) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type CodigoRespuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Codigo        int32                  `protobuf:"varint,1,opt,name=codigo,proto3" json:"codigo,omitempty"`  // Codigo de resultado 0 si fue exitoso
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"` // Añadir mensaje para el cliente
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodigoRespuesta) Reset() {
	*x = CodigoRespuesta{}
	mi := &file_tipos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodigoRespuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodigoRespuesta) ProtoMessage() {}

func (x *CodigoRespuesta) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodigoRespuesta.ProtoReflect.Descriptor instead.
func (*CodigoRespuesta) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{2}
}

func (x *CodigoRespuesta) GetCodigo() int32 {
	if x != nil {
		return x.Codigo
	}
	return 0
}

func (x *CodigoRespuesta) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

type Torneo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Estado        EstadoTorneo           `protobuf:"varint,3,opt,name=estado,proto3,enum=pokemon.EstadoTorneo" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torneo) Reset() {
	*x = Torneo{}
	mi := &file_tipos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torneo) ProtoMessage() {}

func (x *Torneo) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torneo.ProtoReflect.Descriptor instead.
func (*Torneo) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{3}
}

func (x *Torneo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Torneo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Torneo) GetEstado() EstadoTorneo {
	if x != nil {
		return x.Estado
	}
	return EstadoTorneo_TORNEO_ACTIVO
}

type ListaTorneos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torneos       []*Torneo              `protobuf:"bytes,1,rep,name=torneos,proto3" json:"torneos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaTorneos) Reset() {
	*x = ListaTorneos{}
	mi := &file_tipos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaTorneos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaTorneos) ProtoMessage() {}

func (x *ListaTorneos) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaTorneos.ProtoReflect.Descriptor instead.
func (*ListaTorneos) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{4}
}

func (x *ListaTorneos) GetTorneos() []*Torneo {
	if x != nil {
		return x.Torneos
	}
	return nil
}

type RegionString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Region        string                 `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegionString) Reset() {
	*x = RegionString{}
	mi := &file_tipos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegionString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionString) ProtoMessage() {}

func (x *RegionString) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionString.ProtoReflect.Descriptor instead.
func (*RegionString) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{5}
}

func (x *RegionString) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type InscripcionTorneo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntrenadorId  string                 `protobuf:"bytes,1,opt,name=entrenador_id,json=entrenadorId,proto3" json:"entrenador_id,omitempty"`
	TorneoId      string                 `protobuf:"bytes,2,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InscripcionTorneo) Reset() {
	*x = InscripcionTorneo{}
	mi := &file_tipos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionTorneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionTorneo) ProtoMessage() {}

func (x *InscripcionTorneo) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionTorneo.ProtoReflect.Descriptor instead.
func (*InscripcionTorneo) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{6}
}

func (x *InscripcionTorneo) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

func (x *InscripcionTorneo) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

type EntrenadorID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntrenadorID) Reset() {
	*x = EntrenadorID{}
	mi := &file_tipos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntrenadorID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntrenadorID) ProtoMessage() {}

func (x *EntrenadorID) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntrenadorID.ProtoReflect.Descriptor instead.
func (*EntrenadorID) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{7}
}

func (x *EntrenadorID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListaEntrenadores struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entrenadores  []*Entrenador          `protobuf:"bytes,1,rep,name=entrenadores,proto3" json:"entrenadores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaEntrenadores) Reset() {
	*x = ListaEntrenadores{}
	mi := &file_tipos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaEntrenadores) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaEntrenadores) ProtoMessage() {}

func (x *ListaEntrenadores) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaEntrenadores.ProtoReflect.Descriptor instead.
func (*ListaEntrenadores) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{8}
}

func (x *ListaEntrenadores) GetEntrenadores() []*Entrenador {
	if x != nil {
		return x.Entrenadores
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_tipos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{9}
}

var File_tipos_proto protoreflect.FileDescriptor

const file_tipos_proto_rawDesc = "" +
	"\n" +
	"\vtipos.proto\x12\apokemon\"\xb9\x01\n" +
	"\n" +
	"Entrenador\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x18\n" +
	"\aranking\x18\x04 \x01(\x05R\aranking\x121\n" +
	"\x06estado\x18\x05 \x01(\x0e2\x19.pokemon.EstadoEntrenadorR\x06estado\x12\x1e\n" +
	"\n" +
	"suspencion\x18\x06 \x01(\x05R\n" +
	"suspencion\"\xa4\x01\n" +
	"\n" +
	"CombateGym\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\fentrenador_1\x18\x02 \x01(\v2\x13.pokemon.EntrenadorR\ventrenador1\x126\n" +
	"\fentrenador_2\x18\x03 \x01(\v2\x13.pokemon.EntrenadorR\ventrenador2\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\"C\n" +
	"\x0fCodigoRespuesta\x12\x16\n" +
	"\x06codigo\x18\x01 \x01(\x05R\x06codigo\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"_\n" +
	"\x06Torneo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12-\n" +
	"\x06estado\x18\x03 \x01(\x0e2\x15.pokemon.EstadoTorneoR\x06estado\"9\n" +
	"\fListaTorneos\x12)\n" +
	"\atorneos\x18\x01 \x03(\v2\x0f.pokemon.TorneoR\atorneos\"&\n" +
	"\fRegionString\x12\x16\n" +
	"\x06region\x18\x01 \x01(\tR\x06region\"U\n" +
	"\x11InscripcionTorneo\x12#\n" +
	"\rentrenador_id\x18\x01 \x01(\tR\fentrenadorId\x12\x1b\n" +
	"\ttorneo_id\x18\x02 \x01(\tR\btorneoId\"\x1e\n" +
	"\fEntrenadorID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x11ListaEntrenadores\x127\n" +
	"\fentrenadores\x18\x01 \x03(\v2\x13.pokemon.EntrenadorR\fentrenadores\"\a\n" +
	"\x05Empty*]\n" +
	"\x10EstadoEntrenador\x12\x15\n" +
	"\x11ENTRENADOR_ACTIVO\x10\x00\x12\x17\n" +
	"\x13ENTRENADOR_INACTIVO\x10\x01\x12\x19\n" +
	"\x15ENTRENADOR_SUSPENDIDO\x10\x02*N\n" +
	"\fEstadoTorneo\x12\x11\n" +
	"\rTORNEO_ACTIVO\x10\x00\x12\x14\n" +
	"\x10TORNEO_PENDIENTE\x10\x01\x12\x15\n" +
	"\x11TORNEO_FINALIZADO\x10\x02B\x17Z\x15mensajes/PokemonProtob\x06proto3"

var (
	file_tipos_proto_rawDescOnce sync.Once
	file_tipos_proto_rawDescData []byte
)

func file_tipos_proto_rawDescGZIP() []byte {
	file_tipos_proto_rawDescOnce.Do(func() {
		file_tipos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tipos_proto_rawDesc), len(file_tipos_proto_rawDesc)))
	})
	return file_tipos_proto_rawDescData
}

var file_tipos_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tipos_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tipos_proto_goTypes = []any{
	(EstadoEntrenador)(0),     // 0: pokemon.EstadoEntrenador
	(EstadoTorneo)(0),         // 1: pokemon.EstadoTorneo
	(*Entrenador)(nil),        // 2: pokemon.Entrenador
	(*CombateGym)(nil),        // 3: pokemon.CombateGym
	(*CodigoRespuesta)(nil),   // 4: pokemon.CodigoRespuesta
	(*Torneo)(nil),            // 5: pokemon.Torneo
	(*ListaTorneos)(nil),      // 6: pokemon.ListaTorneos
	(*RegionString)(nil),      // 7: pokemon.RegionString
	(*InscripcionTorneo)(nil), // 8: pokemon.InscripcionTorneo
	(*EntrenadorID)(nil),      // 9: pokemon.EntrenadorID
	(*ListaEntrenadores)(nil), // 10: pokemon.ListaEntrenadores
	(*Empty)(nil),             // 11: pokemon.Empty
}
var file_tipos_proto_depIdxs = []int32{
	0, // 0: pokemon.Entrenador.estado:type_name -> pokemon.EstadoEntrenador
	2, // 1: pokemon.CombateGym.entrenador_1:type_name -> pokemon.Entrenador
	2, // 2: pokemon.CombateGym.entrenador_2:type_name -> pokemon.Entrenador
	1, // 3: pokemon.Torneo.estado:type_name -> pokemon.EstadoTorneo
	5, // 4: pokemon.ListaTorneos.torneos:type_name -> pokemon.Torneo
	2, // 5: pokemon.ListaEntrenadores.entrenadores:type_name -> pokemon.Entrenador
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_tipos_proto_init() }
func file_tipos_proto_init() {
	if File_tipos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tipos_proto_rawDesc), len(file_tipos_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tipos_proto_goTypes,
		DependencyIndexes: file_tipos_proto_depIdxs,
		EnumInfos:         file_tipos_proto_enumTypes,
		MessageInfos:      file_tipos_proto_msgTypes,
	}.Build()
	File_tipos_proto = out.File
	file_tipos_proto_goTypes = nil
	file_tipos_proto_depIdxs = nil
}
