// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/mensajes.proto

package servicioMensajes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_mensajes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{0}
}

type Pirata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Recompensa    int32                  `protobuf:"varint,3,opt,name=recompensa,proto3" json:"recompensa,omitempty"`
	Peligrosidad  string                 `protobuf:"bytes,4,opt,name=peligrosidad,proto3" json:"peligrosidad,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pirata) Reset() {
	*x = Pirata{}
	mi := &file_proto_mensajes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pirata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pirata) ProtoMessage() {}

func (x *Pirata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pirata.ProtoReflect.Descriptor instead.
func (*Pirata) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{1}
}

func (x *Pirata) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pirata) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pirata) GetRecompensa() int32 {
	if x != nil {
		return x.Recompensa
	}
	return 0
}

func (x *Pirata) GetPeligrosidad() string {
	if x != nil {
		return x.Peligrosidad
	}
	return ""
}

func (x *Pirata) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type ListaPiratas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Piratas       []*Pirata              `protobuf:"bytes,1,rep,name=piratas,proto3" json:"piratas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListaPiratas) Reset() {
	*x = ListaPiratas{}
	mi := &file_proto_mensajes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListaPiratas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListaPiratas) ProtoMessage() {}

func (x *ListaPiratas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListaPiratas.ProtoReflect.Descriptor instead.
func (*ListaPiratas) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{2}
}

func (x *ListaPiratas) GetPiratas() []*Pirata {
	if x != nil {
		return x.Piratas
	}
	return nil
}

type NpiratasRestantes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cantidad      int32                  `protobuf:"varint,1,opt,name=cantidad,proto3" json:"cantidad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NpiratasRestantes) Reset() {
	*x = NpiratasRestantes{}
	mi := &file_proto_mensajes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NpiratasRestantes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NpiratasRestantes) ProtoMessage() {}

func (x *NpiratasRestantes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NpiratasRestantes.ProtoReflect.Descriptor instead.
func (*NpiratasRestantes) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{3}
}

func (x *NpiratasRestantes) GetCantidad() int32 {
	if x != nil {
		return x.Cantidad
	}
	return 0
}

type EntregaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       int32                  `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Reputacion    int32                  `protobuf:"varint,2,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	Pirata        *Pirata                `protobuf:"bytes,3,opt,name=pirata,proto3" json:"pirata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntregaRequest) Reset() {
	*x = EntregaRequest{}
	mi := &file_proto_mensajes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaRequest) ProtoMessage() {}

func (x *EntregaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaRequest.ProtoReflect.Descriptor instead.
func (*EntregaRequest) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{4}
}

func (x *EntregaRequest) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *EntregaRequest) GetReputacion() int32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

func (x *EntregaRequest) GetPirata() *Pirata {
	if x != nil {
		return x.Pirata
	}
	return nil
}

type EntregaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Estado        string                 `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Pago          int32                  `protobuf:"varint,2,opt,name=pago,proto3" json:"pago,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntregaResponse) Reset() {
	*x = EntregaResponse{}
	mi := &file_proto_mensajes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntregaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntregaResponse) ProtoMessage() {}

func (x *EntregaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntregaResponse.ProtoReflect.Descriptor instead.
func (*EntregaResponse) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{5}
}

func (x *EntregaResponse) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *EntregaResponse) GetPago() int32 {
	if x != nil {
		return x.Pago
	}
	return 0
}

type ActualizarReputacionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reputacion    int32                  `protobuf:"varint,1,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	IdPirata      int32                  `protobuf:"varint,2,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	Estado        string                 `protobuf:"bytes,3,opt,name=estado,proto3" json:"estado,omitempty"`
	Submundo      bool                   `protobuf:"varint,4,opt,name=submundo,proto3" json:"submundo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarReputacionRequest) Reset() {
	*x = ActualizarReputacionRequest{}
	mi := &file_proto_mensajes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarReputacionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarReputacionRequest) ProtoMessage() {}

func (x *ActualizarReputacionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarReputacionRequest.ProtoReflect.Descriptor instead.
func (*ActualizarReputacionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{6}
}

func (x *ActualizarReputacionRequest) GetReputacion() int32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

func (x *ActualizarReputacionRequest) GetIdPirata() int32 {
	if x != nil {
		return x.IdPirata
	}
	return 0
}

func (x *ActualizarReputacionRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *ActualizarReputacionRequest) GetSubmundo() bool {
	if x != nil {
		return x.Submundo
	}
	return false
}

type BasicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicRequest) Reset() {
	*x = BasicRequest{}
	mi := &file_proto_mensajes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicRequest) ProtoMessage() {}

func (x *BasicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicRequest.ProtoReflect.Descriptor instead.
func (*BasicRequest) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{7}
}

func (x *BasicRequest) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type BasicResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicResponse) Reset() {
	*x = BasicResponse{}
	mi := &file_proto_mensajes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicResponse) ProtoMessage() {}

func (x *BasicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicResponse.ProtoReflect.Descriptor instead.
func (*BasicResponse) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{8}
}

func (x *BasicResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ActualizarReputacionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reputacion    int32                  `protobuf:"varint,1,opt,name=reputacion,proto3" json:"reputacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarReputacionResponse) Reset() {
	*x = ActualizarReputacionResponse{}
	mi := &file_proto_mensajes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarReputacionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarReputacionResponse) ProtoMessage() {}

func (x *ActualizarReputacionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarReputacionResponse.ProtoReflect.Descriptor instead.
func (*ActualizarReputacionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{9}
}

func (x *ActualizarReputacionResponse) GetReputacion() int32 {
	if x != nil {
		return x.Reputacion
	}
	return 0
}

type PirataCapturado struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdPirata      int32                  `protobuf:"varint,1,opt,name=id_pirata,json=idPirata,proto3" json:"id_pirata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PirataCapturado) Reset() {
	*x = PirataCapturado{}
	mi := &file_proto_mensajes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PirataCapturado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PirataCapturado) ProtoMessage() {}

func (x *PirataCapturado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mensajes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PirataCapturado.ProtoReflect.Descriptor instead.
func (*PirataCapturado) Descriptor() ([]byte, []int) {
	return file_proto_mensajes_proto_rawDescGZIP(), []int{10}
}

func (x *PirataCapturado) GetIdPirata() int32 {
	if x != nil {
		return x.IdPirata
	}
	return 0
}

var File_proto_mensajes_proto protoreflect.FileDescriptor

const file_proto_mensajes_proto_rawDesc = "" +
	"\n" +
	"\x14proto/mensajes.proto\x12\x10serviciomensajes\"\a\n" +
	"\x05Empty\"\x8c\x01\n" +
	"\x06Pirata\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1e\n" +
	"\n" +
	"recompensa\x18\x03 \x01(\x05R\n" +
	"recompensa\x12\"\n" +
	"\fpeligrosidad\x18\x04 \x01(\tR\fpeligrosidad\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\"B\n" +
	"\fListaPiratas\x122\n" +
	"\apiratas\x18\x01 \x03(\v2\x18.serviciomensajes.PirataR\apiratas\"/\n" +
	"\x11NpiratasRestantes\x12\x1a\n" +
	"\bcantidad\x18\x01 \x01(\x05R\bcantidad\"|\n" +
	"\x0eEntregaRequest\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x05R\abalance\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x02 \x01(\x05R\n" +
	"reputacion\x120\n" +
	"\x06pirata\x18\x03 \x01(\v2\x18.serviciomensajes.PirataR\x06pirata\"=\n" +
	"\x0fEntregaResponse\x12\x16\n" +
	"\x06estado\x18\x01 \x01(\tR\x06estado\x12\x12\n" +
	"\x04pago\x18\x02 \x01(\x05R\x04pago\"\x8e\x01\n" +
	"\x1bActualizarReputacionRequest\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x01 \x01(\x05R\n" +
	"reputacion\x12\x1b\n" +
	"\tid_pirata\x18\x02 \x01(\x05R\bidPirata\x12\x16\n" +
	"\x06estado\x18\x03 \x01(\tR\x06estado\x12\x1a\n" +
	"\bsubmundo\x18\x04 \x01(\bR\bsubmundo\" \n" +
	"\fBasicRequest\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"!\n" +
	"\rBasicResponse\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\">\n" +
	"\x1cActualizarReputacionResponse\x12\x1e\n" +
	"\n" +
	"reputacion\x18\x01 \x01(\x05R\n" +
	"reputacion\".\n" +
	"\x0fPirataCapturado\x12\x1b\n" +
	"\tid_pirata\x18\x01 \x01(\x05R\bidPirata2\x9a\x04\n" +
	"\x0fGobiernoService\x12N\n" +
	"\x13ObtenerListaPiratas\x12\x17.serviciomensajes.Empty\x1a\x1e.serviciomensajes.ListaPiratas\x12S\n" +
	"\x18ObtenerListaPiratasTodos\x12\x17.serviciomensajes.Empty\x1a\x1e.serviciomensajes.ListaPiratas\x12q\n" +
	"\x10ResultadoEntrega\x12-.serviciomensajes.ActualizarReputacionRequest\x1a..serviciomensajes.ActualizarReputacionResponse\x12H\n" +
	"\x05Basic\x12\x1e.serviciomensajes.BasicRequest\x1a\x1f.serviciomensajes.BasicResponse\x12X\n" +
	"\x18ObtenerNpiratasRestantes\x12\x17.serviciomensajes.Empty\x1a#.serviciomensajes.NpiratasRestantes\x12K\n" +
	"\rMarcarCaptura\x12!.serviciomensajes.PirataCapturado\x1a\x17.serviciomensajes.Empty2\xf5\x01\n" +
	"\rMarinaService\x12U\n" +
	"\x0eEntregarPirata\x12 .serviciomensajes.EntregaRequest\x1a!.serviciomensajes.EntregaResponse\x12C\n" +
	"\x0fActividadIlegal\x12\x17.serviciomensajes.Empty\x1a\x17.serviciomensajes.Empty\x12H\n" +
	"\x05Basic\x12\x1e.serviciomensajes.BasicRequest\x1a\x1f.serviciomensajes.BasicResponse2\xf6\x01\n" +
	"\x0fSubMundoService\x12U\n" +
	"\x0eEntregarPirata\x12 .serviciomensajes.EntregaRequest\x1a!.serviciomensajes.EntregaResponse\x12B\n" +
	"\x0eActivarRedadas\x12\x17.serviciomensajes.Empty\x1a\x17.serviciomensajes.Empty\x12H\n" +
	"\x05Basic\x12\x1e.serviciomensajes.BasicRequest\x1a\x1f.serviciomensajes.BasicResponseB!Z\x1fproto/mensajes/servicioMensajesb\x06proto3"

var (
	file_proto_mensajes_proto_rawDescOnce sync.Once
	file_proto_mensajes_proto_rawDescData []byte
)

func file_proto_mensajes_proto_rawDescGZIP() []byte {
	file_proto_mensajes_proto_rawDescOnce.Do(func() {
		file_proto_mensajes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mensajes_proto_rawDesc), len(file_proto_mensajes_proto_rawDesc)))
	})
	return file_proto_mensajes_proto_rawDescData
}

var file_proto_mensajes_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_mensajes_proto_goTypes = []any{
	(*Empty)(nil),                        // 0: serviciomensajes.Empty
	(*Pirata)(nil),                       // 1: serviciomensajes.Pirata
	(*ListaPiratas)(nil),                 // 2: serviciomensajes.ListaPiratas
	(*NpiratasRestantes)(nil),            // 3: serviciomensajes.NpiratasRestantes
	(*EntregaRequest)(nil),               // 4: serviciomensajes.EntregaRequest
	(*EntregaResponse)(nil),              // 5: serviciomensajes.EntregaResponse
	(*ActualizarReputacionRequest)(nil),  // 6: serviciomensajes.ActualizarReputacionRequest
	(*BasicRequest)(nil),                 // 7: serviciomensajes.BasicRequest
	(*BasicResponse)(nil),                // 8: serviciomensajes.BasicResponse
	(*ActualizarReputacionResponse)(nil), // 9: serviciomensajes.ActualizarReputacionResponse
	(*PirataCapturado)(nil),              // 10: serviciomensajes.PirataCapturado
}
var file_proto_mensajes_proto_depIdxs = []int32{
	1,  // 0: serviciomensajes.ListaPiratas.piratas:type_name -> serviciomensajes.Pirata
	1,  // 1: serviciomensajes.EntregaRequest.pirata:type_name -> serviciomensajes.Pirata
	0,  // 2: serviciomensajes.GobiernoService.ObtenerListaPiratas:input_type -> serviciomensajes.Empty
	0,  // 3: serviciomensajes.GobiernoService.ObtenerListaPiratasTodos:input_type -> serviciomensajes.Empty
	6,  // 4: serviciomensajes.GobiernoService.ResultadoEntrega:input_type -> serviciomensajes.ActualizarReputacionRequest
	7,  // 5: serviciomensajes.GobiernoService.Basic:input_type -> serviciomensajes.BasicRequest
	0,  // 6: serviciomensajes.GobiernoService.ObtenerNpiratasRestantes:input_type -> serviciomensajes.Empty
	10, // 7: serviciomensajes.GobiernoService.MarcarCaptura:input_type -> serviciomensajes.PirataCapturado
	4,  // 8: serviciomensajes.MarinaService.EntregarPirata:input_type -> serviciomensajes.EntregaRequest
	0,  // 9: serviciomensajes.MarinaService.ActividadIlegal:input_type -> serviciomensajes.Empty
	7,  // 10: serviciomensajes.MarinaService.Basic:input_type -> serviciomensajes.BasicRequest
	4,  // 11: serviciomensajes.SubMundoService.EntregarPirata:input_type -> serviciomensajes.EntregaRequest
	0,  // 12: serviciomensajes.SubMundoService.ActivarRedadas:input_type -> serviciomensajes.Empty
	7,  // 13: serviciomensajes.SubMundoService.Basic:input_type -> serviciomensajes.BasicRequest
	2,  // 14: serviciomensajes.GobiernoService.ObtenerListaPiratas:output_type -> serviciomensajes.ListaPiratas
	2,  // 15: serviciomensajes.GobiernoService.ObtenerListaPiratasTodos:output_type -> serviciomensajes.ListaPiratas
	9,  // 16: serviciomensajes.GobiernoService.ResultadoEntrega:output_type -> serviciomensajes.ActualizarReputacionResponse
	8,  // 17: serviciomensajes.GobiernoService.Basic:output_type -> serviciomensajes.BasicResponse
	3,  // 18: serviciomensajes.GobiernoService.ObtenerNpiratasRestantes:output_type -> serviciomensajes.NpiratasRestantes
	0,  // 19: serviciomensajes.GobiernoService.MarcarCaptura:output_type -> serviciomensajes.Empty
	5,  // 20: serviciomensajes.MarinaService.EntregarPirata:output_type -> serviciomensajes.EntregaResponse
	0,  // 21: serviciomensajes.MarinaService.ActividadIlegal:output_type -> serviciomensajes.Empty
	8,  // 22: serviciomensajes.MarinaService.Basic:output_type -> serviciomensajes.BasicResponse
	5,  // 23: serviciomensajes.SubMundoService.EntregarPirata:output_type -> serviciomensajes.EntregaResponse
	0,  // 24: serviciomensajes.SubMundoService.ActivarRedadas:output_type -> serviciomensajes.Empty
	8,  // 25: serviciomensajes.SubMundoService.Basic:output_type -> serviciomensajes.BasicResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mensajes_proto_init() }
func file_proto_mensajes_proto_init() {
	if File_proto_mensajes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mensajes_proto_rawDesc), len(file_proto_mensajes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_mensajes_proto_goTypes,
		DependencyIndexes: file_proto_mensajes_proto_depIdxs,
		MessageInfos:      file_proto_mensajes_proto_msgTypes,
	}.Build()
	File_proto_mensajes_proto = out.File
	file_proto_mensajes_proto_goTypes = nil
	file_proto_mensajes_proto_depIdxs = nil
}
