// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: mensajes.proto

package MatchmakingProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_mensajes_proto protoreflect.FileDescriptor

const file_mensajes_proto_rawDesc = "" +
	"\n" +
	"\x0emensajes.proto\x12\vmatchmaking\x1a\vtipos.proto2\xaf\x04\n" +
	"\x12MatchmakingService\x12O\n" +
	"\vQueuePlayer\x12\x1e.matchmaking.PlayerInfoRequest\x1a .matchmaking.QueuePlayerResponse\x12V\n" +
	"\x0fGetPlayerStatus\x12 .matchmaking.PlayerStatusRequest\x1a!.matchmaking.PlayerStatusResponse\x12P\n" +
	"\vCancelQueue\x12\x1f.matchmaking.CancelQueueRequest\x1a .matchmaking.CancelQueueResponse\x12e\n" +
	"\x12UpdateServerStatus\x12&.matchmaking.ServerStatusUpdateRequest\x1a'.matchmaking.ServerStatusUpdateResponse\x12T\n" +
	"\x14AdminGetSystemStatus\x12\x19.matchmaking.AdminRequest\x1a!.matchmaking.SystemStatusResponse\x12a\n" +
	"\x16AdminUpdateServerState\x12%.matchmaking.AdminServerUpdateRequest\x1a .matchmaking.AdminUpdateResponse2\xff\x02\n" +
	"\x11GameServerService\x12P\n" +
	"\vAssignMatch\x12\x1f.matchmaking.AssignMatchRequest\x1a .matchmaking.AssignMatchResponse\x12M\n" +
	"\n" +
	"PingServer\x12\x1e.matchmaking.PingServerRequest\x1a\x1f.matchmaking.PingServerResponse\x12n\n" +
	"\x15UpdateGameServerState\x12).matchmaking.UpdateGameServerStateRequest\x1a*.matchmaking.UpdateGameServerStateResponse\x12Y\n" +
	"\x0eGetMatchResult\x12\".matchmaking.GetMatchResultRequest\x1a#.matchmaking.GetMatchResultResponseB\x1bZ\x19mensajes/MatchmakingProtob\x06proto3"

var file_mensajes_proto_goTypes = []any{
	(*PlayerInfoRequest)(nil),             // 0: matchmaking.PlayerInfoRequest
	(*PlayerStatusRequest)(nil),           // 1: matchmaking.PlayerStatusRequest
	(*CancelQueueRequest)(nil),            // 2: matchmaking.CancelQueueRequest
	(*ServerStatusUpdateRequest)(nil),     // 3: matchmaking.ServerStatusUpdateRequest
	(*AdminRequest)(nil),                  // 4: matchmaking.AdminRequest
	(*AdminServerUpdateRequest)(nil),      // 5: matchmaking.AdminServerUpdateRequest
	(*AssignMatchRequest)(nil),            // 6: matchmaking.AssignMatchRequest
	(*PingServerRequest)(nil),             // 7: matchmaking.PingServerRequest
	(*UpdateGameServerStateRequest)(nil),  // 8: matchmaking.UpdateGameServerStateRequest
	(*GetMatchResultRequest)(nil),         // 9: matchmaking.GetMatchResultRequest
	(*QueuePlayerResponse)(nil),           // 10: matchmaking.QueuePlayerResponse
	(*PlayerStatusResponse)(nil),          // 11: matchmaking.PlayerStatusResponse
	(*CancelQueueResponse)(nil),           // 12: matchmaking.CancelQueueResponse
	(*ServerStatusUpdateResponse)(nil),    // 13: matchmaking.ServerStatusUpdateResponse
	(*SystemStatusResponse)(nil),          // 14: matchmaking.SystemStatusResponse
	(*AdminUpdateResponse)(nil),           // 15: matchmaking.AdminUpdateResponse
	(*AssignMatchResponse)(nil),           // 16: matchmaking.AssignMatchResponse
	(*PingServerResponse)(nil),            // 17: matchmaking.PingServerResponse
	(*UpdateGameServerStateResponse)(nil), // 18: matchmaking.UpdateGameServerStateResponse
	(*GetMatchResultResponse)(nil),        // 19: matchmaking.GetMatchResultResponse
}
var file_mensajes_proto_depIdxs = []int32{
	0,  // 0: matchmaking.MatchmakingService.QueuePlayer:input_type -> matchmaking.PlayerInfoRequest
	1,  // 1: matchmaking.MatchmakingService.GetPlayerStatus:input_type -> matchmaking.PlayerStatusRequest
	2,  // 2: matchmaking.MatchmakingService.CancelQueue:input_type -> matchmaking.CancelQueueRequest
	3,  // 3: matchmaking.MatchmakingService.UpdateServerStatus:input_type -> matchmaking.ServerStatusUpdateRequest
	4,  // 4: matchmaking.MatchmakingService.AdminGetSystemStatus:input_type -> matchmaking.AdminRequest
	5,  // 5: matchmaking.MatchmakingService.AdminUpdateServerState:input_type -> matchmaking.AdminServerUpdateRequest
	6,  // 6: matchmaking.GameServerService.AssignMatch:input_type -> matchmaking.AssignMatchRequest
	7,  // 7: matchmaking.GameServerService.PingServer:input_type -> matchmaking.PingServerRequest
	8,  // 8: matchmaking.GameServerService.UpdateGameServerState:input_type -> matchmaking.UpdateGameServerStateRequest
	9,  // 9: matchmaking.GameServerService.GetMatchResult:input_type -> matchmaking.GetMatchResultRequest
	10, // 10: matchmaking.MatchmakingService.QueuePlayer:output_type -> matchmaking.QueuePlayerResponse
	11, // 11: matchmaking.MatchmakingService.GetPlayerStatus:output_type -> matchmaking.PlayerStatusResponse
	12, // 12: matchmaking.MatchmakingService.CancelQueue:output_type -> matchmaking.CancelQueueResponse
	13, // 13: matchmaking.MatchmakingService.UpdateServerStatus:output_type -> matchmaking.ServerStatusUpdateResponse
	14, // 14: matchmaking.MatchmakingService.AdminGetSystemStatus:output_type -> matchmaking.SystemStatusResponse
	15, // 15: matchmaking.MatchmakingService.AdminUpdateServerState:output_type -> matchmaking.AdminUpdateResponse
	16, // 16: matchmaking.GameServerService.AssignMatch:output_type -> matchmaking.AssignMatchResponse
	17, // 17: matchmaking.GameServerService.PingServer:output_type -> matchmaking.PingServerResponse
	18, // 18: matchmaking.GameServerService.UpdateGameServerState:output_type -> matchmaking.UpdateGameServerStateResponse
	19, // 19: matchmaking.GameServerService.GetMatchResult:output_type -> matchmaking.GetMatchResultResponse
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_mensajes_proto_init() }
func file_mensajes_proto_init() {
	if File_mensajes_proto != nil {
		return
	}
	file_tipos_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mensajes_proto_rawDesc), len(file_mensajes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_mensajes_proto_goTypes,
		DependencyIndexes: file_mensajes_proto_depIdxs,
	}.Build()
	File_mensajes_proto = out.File
	file_mensajes_proto_goTypes = nil
	file_mensajes_proto_depIdxs = nil
}
