// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: tipos.proto

package MatchmakingProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStatus int32

const (
	PlayerStatus_IDLE     PlayerStatus = 0
	PlayerStatus_IN_QUEUE PlayerStatus = 1
	PlayerStatus_IN_MATCH PlayerStatus = 2
	PlayerStatus_UNKNOWN  PlayerStatus = 3
)

// Enum value maps for PlayerStatus.
var (
	PlayerStatus_name = map[int32]string{
		0: "IDLE",
		1: "IN_QUEUE",
		2: "IN_MATCH",
		3: "UNKNOWN",
	}
	PlayerStatus_value = map[string]int32{
		"IDLE":     0,
		"IN_QUEUE": 1,
		"IN_MATCH": 2,
		"UNKNOWN":  3,
	}
)

func (x PlayerStatus) Enum() *PlayerStatus {
	p := new(PlayerStatus)
	*p = x
	return p
}

func (x PlayerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tipos_proto_enumTypes[0].Descriptor()
}

func (PlayerStatus) Type() protoreflect.EnumType {
	return &file_tipos_proto_enumTypes[0]
}

func (x PlayerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerStatus.Descriptor instead.
func (PlayerStatus) EnumDescriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{0}
}

type ServerStatus int32

const (
	ServerStatus_DISPONIBLE  ServerStatus = 0
	ServerStatus_OCUPADO     ServerStatus = 1
	ServerStatus_CAIDO       ServerStatus = 2
	ServerStatus_DESCONOCIDO ServerStatus = 3
)

// Enum value maps for ServerStatus.
var (
	ServerStatus_name = map[int32]string{
		0: "DISPONIBLE",
		1: "OCUPADO",
		2: "CAIDO",
		3: "DESCONOCIDO",
	}
	ServerStatus_value = map[string]int32{
		"DISPONIBLE":  0,
		"OCUPADO":     1,
		"CAIDO":       2,
		"DESCONOCIDO": 3,
	}
)

func (x ServerStatus) Enum() *ServerStatus {
	p := new(ServerStatus)
	*p = x
	return p
}

func (x ServerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tipos_proto_enumTypes[1].Descriptor()
}

func (ServerStatus) Type() protoreflect.EnumType {
	return &file_tipos_proto_enumTypes[1]
}

func (x ServerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerStatus.Descriptor instead.
func (ServerStatus) EnumDescriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{1}
}

type VectorClockEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Timestamp     int32                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClockEntry) Reset() {
	*x = VectorClockEntry{}
	mi := &file_tipos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClockEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClockEntry) ProtoMessage() {}

func (x *VectorClockEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClockEntry.ProtoReflect.Descriptor instead.
func (*VectorClockEntry) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{0}
}

func (x *VectorClockEntry) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *VectorClockEntry) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type VectorClock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VectorClockEntry    `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorClock) Reset() {
	*x = VectorClock{}
	mi := &file_tipos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorClock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorClock) ProtoMessage() {}

func (x *VectorClock) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorClock.ProtoReflect.Descriptor instead.
func (*VectorClock) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{1}
}

func (x *VectorClock) GetEntries() []*VectorClockEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// SOLICITAR PARTIDA
type PlayerInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ModePreference int32                  `protobuf:"varint,2,opt,name=modePreference,proto3" json:"modePreference,omitempty"`
	VectorClock    *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerInfoRequest) Reset() {
	*x = PlayerInfoRequest{}
	mi := &file_tipos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfoRequest) ProtoMessage() {}

func (x *PlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*PlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInfoRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerInfoRequest) GetModePreference() int32 {
	if x != nil {
		return x.ModePreference
	}
	return 0
}

func (x *PlayerInfoRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type QueuePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuePlayerResponse) Reset() {
	*x = QueuePlayerResponse{}
	mi := &file_tipos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuePlayerResponse) ProtoMessage() {}

func (x *QueuePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuePlayerResponse.ProtoReflect.Descriptor instead.
func (*QueuePlayerResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{3}
}

func (x *QueuePlayerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *QueuePlayerResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *QueuePlayerResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// SOLICITAR ESTADO
type PlayerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,2,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatusRequest) Reset() {
	*x = PlayerStatusRequest{}
	mi := &file_tipos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatusRequest) ProtoMessage() {}

func (x *PlayerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatusRequest.ProtoReflect.Descriptor instead.
func (*PlayerStatusRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerStatusRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerStatusRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type PlayerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PlayerStatus           `protobuf:"varint,1,opt,name=Status,proto3,enum=matchmaking.PlayerStatus" json:"Status,omitempty"` // IDLE, IN_QUEUE, IN_MATCH
	MatchId       string                 `protobuf:"bytes,2,opt,name=matchId,proto3" json:"matchId,omitempty"`
	ServerAddress string                 `protobuf:"bytes,3,opt,name=serverAddress,proto3" json:"serverAddress,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,4,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatusResponse) Reset() {
	*x = PlayerStatusResponse{}
	mi := &file_tipos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatusResponse) ProtoMessage() {}

func (x *PlayerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatusResponse.ProtoReflect.Descriptor instead.
func (*PlayerStatusResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{5}
}

func (x *PlayerStatusResponse) GetStatus() PlayerStatus {
	if x != nil {
		return x.Status
	}
	return PlayerStatus_IDLE
}

func (x *PlayerStatusResponse) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *PlayerStatusResponse) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *PlayerStatusResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// CANCELAR COLA
type CancelQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,2,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueueRequest) Reset() {
	*x = CancelQueueRequest{}
	mi := &file_tipos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueueRequest) ProtoMessage() {}

func (x *CancelQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueueRequest.ProtoReflect.Descriptor instead.
func (*CancelQueueRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{6}
}

func (x *CancelQueueRequest) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CancelQueueRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type CancelQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelQueueResponse) Reset() {
	*x = CancelQueueResponse{}
	mi := &file_tipos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelQueueResponse) ProtoMessage() {}

func (x *CancelQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelQueueResponse.ProtoReflect.Descriptor instead.
func (*CancelQueueResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{7}
}

func (x *CancelQueueResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *CancelQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CancelQueueResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// ASIGNAR PARTIDA
type AssignMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId1     string                 `protobuf:"bytes,2,opt,name=playerId1,proto3" json:"playerId1,omitempty"`
	PlayerId2     string                 `protobuf:"bytes,3,opt,name=playerId2,proto3" json:"playerId2,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,4,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMatchRequest) Reset() {
	*x = AssignMatchRequest{}
	mi := &file_tipos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMatchRequest) ProtoMessage() {}

func (x *AssignMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMatchRequest.ProtoReflect.Descriptor instead.
func (*AssignMatchRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{8}
}

func (x *AssignMatchRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssignMatchRequest) GetPlayerId1() string {
	if x != nil {
		return x.PlayerId1
	}
	return ""
}

func (x *AssignMatchRequest) GetPlayerId2() string {
	if x != nil {
		return x.PlayerId2
	}
	return ""
}

func (x *AssignMatchRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type AssignMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignMatchResponse) Reset() {
	*x = AssignMatchResponse{}
	mi := &file_tipos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignMatchResponse) ProtoMessage() {}

func (x *AssignMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignMatchResponse.ProtoReflect.Descriptor instead.
func (*AssignMatchResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{9}
}

func (x *AssignMatchResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AssignMatchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AssignMatchResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type PingServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorClock   *VectorClock           `protobuf:"bytes,1,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingServerRequest) Reset() {
	*x = PingServerRequest{}
	mi := &file_tipos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServerRequest) ProtoMessage() {}

func (x *PingServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServerRequest.ProtoReflect.Descriptor instead.
func (*PingServerRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{10}
}

func (x *PingServerRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type PingServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingServerResponse) Reset() {
	*x = PingServerResponse{}
	mi := &file_tipos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingServerResponse) ProtoMessage() {}

func (x *PingServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingServerResponse.ProtoReflect.Descriptor instead.
func (*PingServerResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{11}
}

func (x *PingServerResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *PingServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingServerResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// ACTUALIZAR ESTADO DEL SERVIDOR
type ServerStatusUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	NewStatus     ServerStatus           `protobuf:"varint,2,opt,name=newStatus,proto3,enum=matchmaking.ServerStatus" json:"newStatus,omitempty"`
	ServerAddress string                 `protobuf:"bytes,3,opt,name=serverAddress,proto3" json:"serverAddress,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,4,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusUpdateRequest) Reset() {
	*x = ServerStatusUpdateRequest{}
	mi := &file_tipos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusUpdateRequest) ProtoMessage() {}

func (x *ServerStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*ServerStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{12}
}

func (x *ServerStatusUpdateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerStatusUpdateRequest) GetNewStatus() ServerStatus {
	if x != nil {
		return x.NewStatus
	}
	return ServerStatus_DISPONIBLE
}

func (x *ServerStatusUpdateRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerStatusUpdateRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type ServerStatusUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusUpdateResponse) Reset() {
	*x = ServerStatusUpdateResponse{}
	mi := &file_tipos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusUpdateResponse) ProtoMessage() {}

func (x *ServerStatusUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusUpdateResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{13}
}

func (x *ServerStatusUpdateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ServerStatusUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ServerStatusUpdateResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type AdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VectorClock   *VectorClock           `protobuf:"bytes,1,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminRequest) Reset() {
	*x = AdminRequest{}
	mi := &file_tipos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminRequest) ProtoMessage() {}

func (x *AdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminRequest.ProtoReflect.Descriptor instead.
func (*AdminRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{14}
}

func (x *AdminRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type ServerState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status         ServerStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=matchmaking.ServerStatus" json:"status,omitempty"`
	Address        string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	CurrentMatchId string                 `protobuf:"bytes,4,opt,name=currentMatchId,proto3" json:"currentMatchId,omitempty"`
	VectorClock    *VectorClock           `protobuf:"bytes,5,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerState) Reset() {
	*x = ServerState{}
	mi := &file_tipos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerState) ProtoMessage() {}

func (x *ServerState) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerState.ProtoReflect.Descriptor instead.
func (*ServerState) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{15}
}

func (x *ServerState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServerState) GetStatus() ServerStatus {
	if x != nil {
		return x.Status
	}
	return ServerStatus_DISPONIBLE
}

func (x *ServerState) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerState) GetCurrentMatchId() string {
	if x != nil {
		return x.CurrentMatchId
	}
	return ""
}

func (x *ServerState) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type PlayerQueueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	TimeInQueue   int32                  `protobuf:"varint,2,opt,name=timeInQueue,proto3" json:"timeInQueue,omitempty"` // segundos
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerQueueEntry) Reset() {
	*x = PlayerQueueEntry{}
	mi := &file_tipos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerQueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerQueueEntry) ProtoMessage() {}

func (x *PlayerQueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerQueueEntry.ProtoReflect.Descriptor instead.
func (*PlayerQueueEntry) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{16}
}

func (x *PlayerQueueEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerQueueEntry) GetTimeInQueue() int32 {
	if x != nil {
		return x.TimeInQueue
	}
	return 0
}

func (x *PlayerQueueEntry) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type SystemStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerList    []*ServerState         `protobuf:"bytes,1,rep,name=serverList,proto3" json:"serverList,omitempty"`
	PlayerQueue   []*PlayerQueueEntry    `protobuf:"bytes,2,rep,name=playerQueue,proto3" json:"playerQueue,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemStatusResponse) Reset() {
	*x = SystemStatusResponse{}
	mi := &file_tipos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStatusResponse) ProtoMessage() {}

func (x *SystemStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStatusResponse.ProtoReflect.Descriptor instead.
func (*SystemStatusResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{17}
}

func (x *SystemStatusResponse) GetServerList() []*ServerState {
	if x != nil {
		return x.ServerList
	}
	return nil
}

func (x *SystemStatusResponse) GetPlayerQueue() []*PlayerQueueEntry {
	if x != nil {
		return x.PlayerQueue
	}
	return nil
}

func (x *SystemStatusResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type AdminServerUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	NewStatus     ServerStatus           `protobuf:"varint,2,opt,name=newStatus,proto3,enum=matchmaking.ServerStatus" json:"newStatus,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminServerUpdateRequest) Reset() {
	*x = AdminServerUpdateRequest{}
	mi := &file_tipos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminServerUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminServerUpdateRequest) ProtoMessage() {}

func (x *AdminServerUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminServerUpdateRequest.ProtoReflect.Descriptor instead.
func (*AdminServerUpdateRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{18}
}

func (x *AdminServerUpdateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AdminServerUpdateRequest) GetNewStatus() ServerStatus {
	if x != nil {
		return x.NewStatus
	}
	return ServerStatus_DISPONIBLE
}

func (x *AdminServerUpdateRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type AdminUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminUpdateResponse) Reset() {
	*x = AdminUpdateResponse{}
	mi := &file_tipos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminUpdateResponse) ProtoMessage() {}

func (x *AdminUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminUpdateResponse.ProtoReflect.Descriptor instead.
func (*AdminUpdateResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{19}
}

func (x *AdminUpdateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AdminUpdateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AdminUpdateResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// MATCHMAKER -> GAME SERVER: Actualizar estado del servidor
type UpdateGameServerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	NewStatus     ServerStatus           `protobuf:"varint,2,opt,name=newStatus,proto3,enum=matchmaking.ServerStatus" json:"newStatus,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameServerStateRequest) Reset() {
	*x = UpdateGameServerStateRequest{}
	mi := &file_tipos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameServerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerStateRequest) ProtoMessage() {}

func (x *UpdateGameServerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerStateRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameServerStateRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateGameServerStateRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *UpdateGameServerStateRequest) GetNewStatus() ServerStatus {
	if x != nil {
		return x.NewStatus
	}
	return ServerStatus_DISPONIBLE
}

func (x *UpdateGameServerStateRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type UpdateGameServerStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,3,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameServerStateResponse) Reset() {
	*x = UpdateGameServerStateResponse{}
	mi := &file_tipos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameServerStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameServerStateResponse) ProtoMessage() {}

func (x *UpdateGameServerStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameServerStateResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameServerStateResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateGameServerStateResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *UpdateGameServerStateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateGameServerStateResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

// SOLICITAR RESULTADO DE PARTIDA
type GetMatchResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MatchId       string                 `protobuf:"bytes,1,opt,name=matchId,proto3" json:"matchId,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,2,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResultRequest) Reset() {
	*x = GetMatchResultRequest{}
	mi := &file_tipos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResultRequest) ProtoMessage() {}

func (x *GetMatchResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResultRequest.ProtoReflect.Descriptor instead.
func (*GetMatchResultRequest) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{22}
}

func (x *GetMatchResultRequest) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GetMatchResultRequest) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

type GetMatchResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WinnerId      string                 `protobuf:"bytes,3,opt,name=winnerId,proto3" json:"winnerId,omitempty"`
	LoserId       string                 `protobuf:"bytes,4,opt,name=loserId,proto3" json:"loserId,omitempty"`
	VectorClock   *VectorClock           `protobuf:"bytes,5,opt,name=vectorClock,proto3" json:"vectorClock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMatchResultResponse) Reset() {
	*x = GetMatchResultResponse{}
	mi := &file_tipos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMatchResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMatchResultResponse) ProtoMessage() {}

func (x *GetMatchResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tipos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMatchResultResponse.ProtoReflect.Descriptor instead.
func (*GetMatchResultResponse) Descriptor() ([]byte, []int) {
	return file_tipos_proto_rawDescGZIP(), []int{23}
}

func (x *GetMatchResultResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *GetMatchResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetMatchResultResponse) GetWinnerId() string {
	if x != nil {
		return x.WinnerId
	}
	return ""
}

func (x *GetMatchResultResponse) GetLoserId() string {
	if x != nil {
		return x.LoserId
	}
	return ""
}

func (x *GetMatchResultResponse) GetVectorClock() *VectorClock {
	if x != nil {
		return x.VectorClock
	}
	return nil
}

var File_tipos_proto protoreflect.FileDescriptor

const file_tipos_proto_rawDesc = "" +
	"\n" +
	"\vtipos.proto\x12\vmatchmaking\"L\n" +
	"\x10VectorClockEntry\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x05R\ttimestamp\"F\n" +
	"\vVectorClock\x127\n" +
	"\aentries\x18\x01 \x03(\v2\x1d.matchmaking.VectorClockEntryR\aentries\"\x93\x01\n" +
	"\x11PlayerInfoRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12&\n" +
	"\x0emodePreference\x18\x02 \x01(\x05R\x0emodePreference\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8b\x01\n" +
	"\x13QueuePlayerResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"m\n" +
	"\x13PlayerStatusRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\vvectorClock\x18\x02 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xc5\x01\n" +
	"\x14PlayerStatusResponse\x121\n" +
	"\x06Status\x18\x01 \x01(\x0e2\x19.matchmaking.PlayerStatusR\x06Status\x12\x18\n" +
	"\amatchId\x18\x02 \x01(\tR\amatchId\x12$\n" +
	"\rserverAddress\x18\x03 \x01(\tR\rserverAddress\x12:\n" +
	"\vvectorClock\x18\x04 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"l\n" +
	"\x12CancelQueueRequest\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12:\n" +
	"\vvectorClock\x18\x02 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8b\x01\n" +
	"\x13CancelQueueResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x9c\x01\n" +
	"\x12AssignMatchRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tplayerId1\x18\x02 \x01(\tR\tplayerId1\x12\x1c\n" +
	"\tplayerId2\x18\x03 \x01(\tR\tplayerId2\x12:\n" +
	"\vvectorClock\x18\x04 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8b\x01\n" +
	"\x13AssignMatchResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"O\n" +
	"\x11PingServerRequest\x12:\n" +
	"\vvectorClock\x18\x01 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8a\x01\n" +
	"\x12PingServerResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xd2\x01\n" +
	"\x19ServerStatusUpdateRequest\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x127\n" +
	"\tnewStatus\x18\x02 \x01(\x0e2\x19.matchmaking.ServerStatusR\tnewStatus\x12$\n" +
	"\rserverAddress\x18\x03 \x01(\tR\rserverAddress\x12:\n" +
	"\vvectorClock\x18\x04 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x92\x01\n" +
	"\x1aServerStatusUpdateResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"J\n" +
	"\fAdminRequest\x12:\n" +
	"\vvectorClock\x18\x01 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xce\x01\n" +
	"\vServerState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.matchmaking.ServerStatusR\x06status\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12&\n" +
	"\x0ecurrentMatchId\x18\x04 \x01(\tR\x0ecurrentMatchId\x12:\n" +
	"\vvectorClock\x18\x05 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8c\x01\n" +
	"\x10PlayerQueueEntry\x12\x1a\n" +
	"\bplayerId\x18\x01 \x01(\tR\bplayerId\x12 \n" +
	"\vtimeInQueue\x18\x02 \x01(\x05R\vtimeInQueue\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xcd\x01\n" +
	"\x14SystemStatusResponse\x128\n" +
	"\n" +
	"serverList\x18\x01 \x03(\v2\x18.matchmaking.ServerStateR\n" +
	"serverList\x12?\n" +
	"\vplayerQueue\x18\x02 \x03(\v2\x1d.matchmaking.PlayerQueueEntryR\vplayerQueue\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xab\x01\n" +
	"\x18AdminServerUpdateRequest\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x127\n" +
	"\tnewStatus\x18\x02 \x01(\x0e2\x19.matchmaking.ServerStatusR\tnewStatus\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x8b\x01\n" +
	"\x13AdminUpdateResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xaf\x01\n" +
	"\x1cUpdateGameServerStateRequest\x12\x1a\n" +
	"\bserverId\x18\x01 \x01(\tR\bserverId\x127\n" +
	"\tnewStatus\x18\x02 \x01(\x0e2\x19.matchmaking.ServerStatusR\tnewStatus\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\x95\x01\n" +
	"\x1dUpdateGameServerStateResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\vvectorClock\x18\x03 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"m\n" +
	"\x15GetMatchResultRequest\x12\x18\n" +
	"\amatchId\x18\x01 \x01(\tR\amatchId\x12:\n" +
	"\vvectorClock\x18\x02 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock\"\xc4\x01\n" +
	"\x16GetMatchResultResponse\x12\x1e\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bwinnerId\x18\x03 \x01(\tR\bwinnerId\x12\x18\n" +
	"\aloserId\x18\x04 \x01(\tR\aloserId\x12:\n" +
	"\vvectorClock\x18\x05 \x01(\v2\x18.matchmaking.VectorClockR\vvectorClock*A\n" +
	"\fPlayerStatus\x12\b\n" +
	"\x04IDLE\x10\x00\x12\f\n" +
	"\bIN_QUEUE\x10\x01\x12\f\n" +
	"\bIN_MATCH\x10\x02\x12\v\n" +
	"\aUNKNOWN\x10\x03*G\n" +
	"\fServerStatus\x12\x0e\n" +
	"\n" +
	"DISPONIBLE\x10\x00\x12\v\n" +
	"\aOCUPADO\x10\x01\x12\t\n" +
	"\x05CAIDO\x10\x02\x12\x0f\n" +
	"\vDESCONOCIDO\x10\x03B\x1bZ\x19mensajes/MatchmakingProtob\x06proto3"

var (
	file_tipos_proto_rawDescOnce sync.Once
	file_tipos_proto_rawDescData []byte
)

func file_tipos_proto_rawDescGZIP() []byte {
	file_tipos_proto_rawDescOnce.Do(func() {
		file_tipos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tipos_proto_rawDesc), len(file_tipos_proto_rawDesc)))
	})
	return file_tipos_proto_rawDescData
}

var file_tipos_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tipos_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_tipos_proto_goTypes = []any{
	(PlayerStatus)(0),                     // 0: matchmaking.PlayerStatus
	(ServerStatus)(0),                     // 1: matchmaking.ServerStatus
	(*VectorClockEntry)(nil),              // 2: matchmaking.VectorClockEntry
	(*VectorClock)(nil),                   // 3: matchmaking.VectorClock
	(*PlayerInfoRequest)(nil),             // 4: matchmaking.PlayerInfoRequest
	(*QueuePlayerResponse)(nil),           // 5: matchmaking.QueuePlayerResponse
	(*PlayerStatusRequest)(nil),           // 6: matchmaking.PlayerStatusRequest
	(*PlayerStatusResponse)(nil),          // 7: matchmaking.PlayerStatusResponse
	(*CancelQueueRequest)(nil),            // 8: matchmaking.CancelQueueRequest
	(*CancelQueueResponse)(nil),           // 9: matchmaking.CancelQueueResponse
	(*AssignMatchRequest)(nil),            // 10: matchmaking.AssignMatchRequest
	(*AssignMatchResponse)(nil),           // 11: matchmaking.AssignMatchResponse
	(*PingServerRequest)(nil),             // 12: matchmaking.PingServerRequest
	(*PingServerResponse)(nil),            // 13: matchmaking.PingServerResponse
	(*ServerStatusUpdateRequest)(nil),     // 14: matchmaking.ServerStatusUpdateRequest
	(*ServerStatusUpdateResponse)(nil),    // 15: matchmaking.ServerStatusUpdateResponse
	(*AdminRequest)(nil),                  // 16: matchmaking.AdminRequest
	(*ServerState)(nil),                   // 17: matchmaking.ServerState
	(*PlayerQueueEntry)(nil),              // 18: matchmaking.PlayerQueueEntry
	(*SystemStatusResponse)(nil),          // 19: matchmaking.SystemStatusResponse
	(*AdminServerUpdateRequest)(nil),      // 20: matchmaking.AdminServerUpdateRequest
	(*AdminUpdateResponse)(nil),           // 21: matchmaking.AdminUpdateResponse
	(*UpdateGameServerStateRequest)(nil),  // 22: matchmaking.UpdateGameServerStateRequest
	(*UpdateGameServerStateResponse)(nil), // 23: matchmaking.UpdateGameServerStateResponse
	(*GetMatchResultRequest)(nil),         // 24: matchmaking.GetMatchResultRequest
	(*GetMatchResultResponse)(nil),        // 25: matchmaking.GetMatchResultResponse
}
var file_tipos_proto_depIdxs = []int32{
	2,  // 0: matchmaking.VectorClock.entries:type_name -> matchmaking.VectorClockEntry
	3,  // 1: matchmaking.PlayerInfoRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 2: matchmaking.QueuePlayerResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 3: matchmaking.PlayerStatusRequest.vectorClock:type_name -> matchmaking.VectorClock
	0,  // 4: matchmaking.PlayerStatusResponse.Status:type_name -> matchmaking.PlayerStatus
	3,  // 5: matchmaking.PlayerStatusResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 6: matchmaking.CancelQueueRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 7: matchmaking.CancelQueueResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 8: matchmaking.AssignMatchRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 9: matchmaking.AssignMatchResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 10: matchmaking.PingServerRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 11: matchmaking.PingServerResponse.vectorClock:type_name -> matchmaking.VectorClock
	1,  // 12: matchmaking.ServerStatusUpdateRequest.newStatus:type_name -> matchmaking.ServerStatus
	3,  // 13: matchmaking.ServerStatusUpdateRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 14: matchmaking.ServerStatusUpdateResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 15: matchmaking.AdminRequest.vectorClock:type_name -> matchmaking.VectorClock
	1,  // 16: matchmaking.ServerState.status:type_name -> matchmaking.ServerStatus
	3,  // 17: matchmaking.ServerState.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 18: matchmaking.PlayerQueueEntry.vectorClock:type_name -> matchmaking.VectorClock
	17, // 19: matchmaking.SystemStatusResponse.serverList:type_name -> matchmaking.ServerState
	18, // 20: matchmaking.SystemStatusResponse.playerQueue:type_name -> matchmaking.PlayerQueueEntry
	3,  // 21: matchmaking.SystemStatusResponse.vectorClock:type_name -> matchmaking.VectorClock
	1,  // 22: matchmaking.AdminServerUpdateRequest.newStatus:type_name -> matchmaking.ServerStatus
	3,  // 23: matchmaking.AdminServerUpdateRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 24: matchmaking.AdminUpdateResponse.vectorClock:type_name -> matchmaking.VectorClock
	1,  // 25: matchmaking.UpdateGameServerStateRequest.newStatus:type_name -> matchmaking.ServerStatus
	3,  // 26: matchmaking.UpdateGameServerStateRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 27: matchmaking.UpdateGameServerStateResponse.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 28: matchmaking.GetMatchResultRequest.vectorClock:type_name -> matchmaking.VectorClock
	3,  // 29: matchmaking.GetMatchResultResponse.vectorClock:type_name -> matchmaking.VectorClock
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_tipos_proto_init() }
func file_tipos_proto_init() {
	if File_tipos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tipos_proto_rawDesc), len(file_tipos_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tipos_proto_goTypes,
		DependencyIndexes: file_tipos_proto_depIdxs,
		EnumInfos:         file_tipos_proto_enumTypes,
		MessageInfos:      file_tipos_proto_msgTypes,
	}.Build()
	File_tipos_proto = out.File
	file_tipos_proto_goTypes = nil
	file_tipos_proto_depIdxs = nil
}
