// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: mensajes.proto

package PokemonProto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicioLCP_ObtenerTorneos_FullMethodName       = "/pokemon.ServicioLCP/ObtenerTorneos"
	ServicioLCP_ObtenerTorneosRegion_FullMethodName = "/pokemon.ServicioLCP/ObtenerTorneosRegion"
	ServicioLCP_InscribirEnTorneo_FullMethodName    = "/pokemon.ServicioLCP/InscribirEnTorneo"
	ServicioLCP_RegistrarEntrenador_FullMethodName  = "/pokemon.ServicioLCP/RegistrarEntrenador"
	ServicioLCP_ExisteEntrenador_FullMethodName     = "/pokemon.ServicioLCP/ExisteEntrenador"
	ServicioLCP_ObtenerEntrenador_FullMethodName    = "/pokemon.ServicioLCP/ObtenerEntrenador"
)

// ServicioLCPClient is the client API for ServicioLCP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicioLCPClient interface {
	ObtenerTorneos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaTorneos, error)
	ObtenerTorneosRegion(ctx context.Context, in *RegionString, opts ...grpc.CallOption) (*ListaTorneos, error)
	InscribirEnTorneo(ctx context.Context, in *InscripcionTorneo, opts ...grpc.CallOption) (*CodigoRespuesta, error)
	RegistrarEntrenador(ctx context.Context, in *Entrenador, opts ...grpc.CallOption) (*CodigoRespuesta, error)
	ExisteEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*CodigoRespuesta, error)
	ObtenerEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*Entrenador, error)
}

type servicioLCPClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioLCPClient(cc grpc.ClientConnInterface) ServicioLCPClient {
	return &servicioLCPClient{cc}
}

func (c *servicioLCPClient) ObtenerTorneos(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ListaTorneos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaTorneos)
	err := c.cc.Invoke(ctx, ServicioLCP_ObtenerTorneos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioLCPClient) ObtenerTorneosRegion(ctx context.Context, in *RegionString, opts ...grpc.CallOption) (*ListaTorneos, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaTorneos)
	err := c.cc.Invoke(ctx, ServicioLCP_ObtenerTorneosRegion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioLCPClient) InscribirEnTorneo(ctx context.Context, in *InscripcionTorneo, opts ...grpc.CallOption) (*CodigoRespuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodigoRespuesta)
	err := c.cc.Invoke(ctx, ServicioLCP_InscribirEnTorneo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioLCPClient) RegistrarEntrenador(ctx context.Context, in *Entrenador, opts ...grpc.CallOption) (*CodigoRespuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodigoRespuesta)
	err := c.cc.Invoke(ctx, ServicioLCP_RegistrarEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioLCPClient) ExisteEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*CodigoRespuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodigoRespuesta)
	err := c.cc.Invoke(ctx, ServicioLCP_ExisteEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicioLCPClient) ObtenerEntrenador(ctx context.Context, in *EntrenadorID, opts ...grpc.CallOption) (*Entrenador, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Entrenador)
	err := c.cc.Invoke(ctx, ServicioLCP_ObtenerEntrenador_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioLCPServer is the server API for ServicioLCP service.
// All implementations must embed UnimplementedServicioLCPServer
// for forward compatibility.
type ServicioLCPServer interface {
	ObtenerTorneos(context.Context, *Empty) (*ListaTorneos, error)
	ObtenerTorneosRegion(context.Context, *RegionString) (*ListaTorneos, error)
	InscribirEnTorneo(context.Context, *InscripcionTorneo) (*CodigoRespuesta, error)
	RegistrarEntrenador(context.Context, *Entrenador) (*CodigoRespuesta, error)
	ExisteEntrenador(context.Context, *EntrenadorID) (*CodigoRespuesta, error)
	ObtenerEntrenador(context.Context, *EntrenadorID) (*Entrenador, error)
	mustEmbedUnimplementedServicioLCPServer()
}

// UnimplementedServicioLCPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioLCPServer struct{}

func (UnimplementedServicioLCPServer) ObtenerTorneos(context.Context, *Empty) (*ListaTorneos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerTorneos not implemented")
}
func (UnimplementedServicioLCPServer) ObtenerTorneosRegion(context.Context, *RegionString) (*ListaTorneos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerTorneosRegion not implemented")
}
func (UnimplementedServicioLCPServer) InscribirEnTorneo(context.Context, *InscripcionTorneo) (*CodigoRespuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InscribirEnTorneo not implemented")
}
func (UnimplementedServicioLCPServer) RegistrarEntrenador(context.Context, *Entrenador) (*CodigoRespuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistrarEntrenador not implemented")
}
func (UnimplementedServicioLCPServer) ExisteEntrenador(context.Context, *EntrenadorID) (*CodigoRespuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExisteEntrenador not implemented")
}
func (UnimplementedServicioLCPServer) ObtenerEntrenador(context.Context, *EntrenadorID) (*Entrenador, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ObtenerEntrenador not implemented")
}
func (UnimplementedServicioLCPServer) mustEmbedUnimplementedServicioLCPServer() {}
func (UnimplementedServicioLCPServer) testEmbeddedByValue()                     {}

// UnsafeServicioLCPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioLCPServer will
// result in compilation errors.
type UnsafeServicioLCPServer interface {
	mustEmbedUnimplementedServicioLCPServer()
}

func RegisterServicioLCPServer(s grpc.ServiceRegistrar, srv ServicioLCPServer) {
	// If the following call pancis, it indicates UnimplementedServicioLCPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioLCP_ServiceDesc, srv)
}

func _ServicioLCP_ObtenerTorneos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).ObtenerTorneos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_ObtenerTorneos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).ObtenerTorneos(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioLCP_ObtenerTorneosRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).ObtenerTorneosRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_ObtenerTorneosRegion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).ObtenerTorneosRegion(ctx, req.(*RegionString))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioLCP_InscribirEnTorneo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InscripcionTorneo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).InscribirEnTorneo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_InscribirEnTorneo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).InscribirEnTorneo(ctx, req.(*InscripcionTorneo))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioLCP_RegistrarEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Entrenador)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).RegistrarEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_RegistrarEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).RegistrarEntrenador(ctx, req.(*Entrenador))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioLCP_ExisteEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntrenadorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).ExisteEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_ExisteEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).ExisteEntrenador(ctx, req.(*EntrenadorID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicioLCP_ObtenerEntrenador_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntrenadorID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioLCPServer).ObtenerEntrenador(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioLCP_ObtenerEntrenador_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioLCPServer).ObtenerEntrenador(ctx, req.(*EntrenadorID))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicioLCP_ServiceDesc is the grpc.ServiceDesc for ServicioLCP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioLCP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.ServicioLCP",
	HandlerType: (*ServicioLCPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ObtenerTorneos",
			Handler:    _ServicioLCP_ObtenerTorneos_Handler,
		},
		{
			MethodName: "ObtenerTorneosRegion",
			Handler:    _ServicioLCP_ObtenerTorneosRegion_Handler,
		},
		{
			MethodName: "InscribirEnTorneo",
			Handler:    _ServicioLCP_InscribirEnTorneo_Handler,
		},
		{
			MethodName: "RegistrarEntrenador",
			Handler:    _ServicioLCP_RegistrarEntrenador_Handler,
		},
		{
			MethodName: "ExisteEntrenador",
			Handler:    _ServicioLCP_ExisteEntrenador_Handler,
		},
		{
			MethodName: "ObtenerEntrenador",
			Handler:    _ServicioLCP_ObtenerEntrenador_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mensajes.proto",
}

const (
	ServicioGym_AsignarCombate_FullMethodName = "/pokemon.ServicioGym/AsignarCombate"
)

// ServicioGymClient is the client API for ServicioGym service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicioGymClient interface {
	AsignarCombate(ctx context.Context, in *CombateGym, opts ...grpc.CallOption) (*CodigoRespuesta, error)
}

type servicioGymClient struct {
	cc grpc.ClientConnInterface
}

func NewServicioGymClient(cc grpc.ClientConnInterface) ServicioGymClient {
	return &servicioGymClient{cc}
}

func (c *servicioGymClient) AsignarCombate(ctx context.Context, in *CombateGym, opts ...grpc.CallOption) (*CodigoRespuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CodigoRespuesta)
	err := c.cc.Invoke(ctx, ServicioGym_AsignarCombate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicioGymServer is the server API for ServicioGym service.
// All implementations must embed UnimplementedServicioGymServer
// for forward compatibility.
type ServicioGymServer interface {
	AsignarCombate(context.Context, *CombateGym) (*CodigoRespuesta, error)
	mustEmbedUnimplementedServicioGymServer()
}

// UnimplementedServicioGymServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicioGymServer struct{}

func (UnimplementedServicioGymServer) AsignarCombate(context.Context, *CombateGym) (*CodigoRespuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AsignarCombate not implemented")
}
func (UnimplementedServicioGymServer) mustEmbedUnimplementedServicioGymServer() {}
func (UnimplementedServicioGymServer) testEmbeddedByValue()                     {}

// UnsafeServicioGymServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicioGymServer will
// result in compilation errors.
type UnsafeServicioGymServer interface {
	mustEmbedUnimplementedServicioGymServer()
}

func RegisterServicioGymServer(s grpc.ServiceRegistrar, srv ServicioGymServer) {
	// If the following call pancis, it indicates UnimplementedServicioGymServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicioGym_ServiceDesc, srv)
}

func _ServicioGym_AsignarCombate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CombateGym)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicioGymServer).AsignarCombate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicioGym_AsignarCombate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicioGymServer).AsignarCombate(ctx, req.(*CombateGym))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicioGym_ServiceDesc is the grpc.ServiceDesc for ServicioGym service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicioGym_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.ServicioGym",
	HandlerType: (*ServicioGymServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AsignarCombate",
			Handler:    _ServicioGym_AsignarCombate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mensajes.proto",
}
